---
# tasks file for mkcert | EL Family

- name: EL Family | Downloading archive for {{ mkcert_app }} {{ mkcert_version }} to {{ mkcert_bin_path }}
  ansible.builtin.get_url:
    url: "{{ mkcert_dl_url }}"
    dest: "{{ mkcert_bin_path }}/{{ mkcert_app }}"
    owner: "{{ mkcert_file_owner }}"
    group: "{{ mkcert_file_group }}"
    mode: "{{ mkcert_file_mode }}"
